import { Service, ServiceRequest, Tenant, User } from "@/types";

export const tenants: Tenant[] = [
  {
    id: "tenant-beirut",
    slug: "beirut-municipality",
    name: "Beirut Municipality",
    region: "Beirut",
  },
  {
    id: "tenant-jounieh",
    slug: "jounieh-municipality",
    name: "Jounieh Municipality",
    region: "Keserwan",
  },
  {
    id: "tenant-zahle",
    slug: "zahle-municipality",
    name: "Zahle Municipality",
    region: "Bekaa",
  },
];

export const demoUsers: User[] = [
  {
    id: "user-1",
    tenantId: "tenant-beirut",
    fullName: "Maya Haddad",
    email: "maya.haddad@example.com",
    role: "citizen",
    municipality: "Beirut Municipality",
  },
  {
    id: "user-2",
    tenantId: "tenant-beirut",
    fullName: "Karim Nader",
    email: "karim.nader@beirut.gov.lb",
    role: "employee",
    municipality: "Beirut Municipality",
  },
  {
    id: "user-3",
    tenantId: "tenant-beirut",
    fullName: "Rana Khoury",
    email: "rana.khoury@beirut.gov.lb",
    role: "municipality_admin",
    municipality: "Beirut Municipality",
  },
  {
    id: "user-4",
    tenantId: null,
    fullName: "Platform Operator",
    email: "platform@civicflow.io",
    role: "super_admin",
    municipality: "Platform",
  },
];

export const services: Service[] = [
  {
    id: "service-1",
    tenantId: "tenant-beirut",
    title: "Residency Certificate",
    category: "Civil Records",
    description: "Issue an official municipal residency certificate.",
    estimatedDays: 3,
  },
  {
    id: "service-2",
    tenantId: "tenant-beirut",
    title: "Business Permit",
    category: "Licensing",
    description: "Apply for a new municipal business permit.",
    estimatedDays: 10,
  },
  {
    id: "service-3",
    tenantId: "tenant-beirut",
    title: "Building Complaint",
    category: "Urban Management",
    description: "Submit a complaint related to construction or zoning.",
    estimatedDays: 5,
  },
  {
    id: "service-4",
    tenantId: "tenant-beirut",
    title: "Road Maintenance Request",
    category: "Public Works",
    description: "Report potholes, damaged sidewalks, or street repairs.",
    estimatedDays: 7,
  },
  {
    id: "service-5",
    tenantId: "tenant-beirut",
    title: "Streetlight Repair",
    category: "Public Works",
    description: "Request repair for broken or unsafe public lighting.",
    estimatedDays: 4,
  },
  {
    id: "service-6",
    tenantId: "tenant-beirut",
    title: "Waste Collection Issue",
    category: "Sanitation",
    description: "Report missed collection, overflowing bins, or dumping.",
    estimatedDays: 2,
  },
  {
    id: "service-7",
    tenantId: "tenant-beirut",
    title: "Tree Pruning Request",
    category: "Parks and Environment",
    description: "Request pruning for trees affecting roads or buildings.",
    estimatedDays: 6,
  },
  {
    id: "service-8",
    tenantId: "tenant-beirut",
    title: "Event Permit",
    category: "Licensing",
    description: "Apply to host a public event in municipal spaces.",
    estimatedDays: 8,
  },
  {
    id: "service-9",
    tenantId: "tenant-beirut",
    title: "Parking Obstruction Report",
    category: "Traffic and Parking",
    description: "Report blocked entrances, illegal parking, or obstructions.",
    estimatedDays: 3,
  },
  {
    id: "service-10",
    tenantId: "tenant-beirut",
    title: "Water Leak Report",
    category: "Infrastructure",
    description: "Report visible water leaks on streets or public property.",
    estimatedDays: 2,
  },
  {
    id: "service-11",
    tenantId: "tenant-beirut",
    title: "Sidewalk Occupancy Permit",
    category: "Licensing",
    description: "Request permission for temporary sidewalk or storefront use.",
    estimatedDays: 9,
  },
  {
    id: "service-12",
    tenantId: "tenant-beirut",
    title: "Public Garden Maintenance",
    category: "Parks and Environment",
    description: "Request maintenance for public gardens, benches, or play areas.",
    estimatedDays: 6,
  },
  {
    id: "service-13",
    tenantId: "tenant-beirut",
    title: "Municipal Tax Statement",
    category: "Finance",
    description: "Request an official statement for municipal taxes or fees.",
    estimatedDays: 4,
  },
  {
    id: "service-14",
    tenantId: "tenant-beirut",
    title: "Signage Permit",
    category: "Licensing",
    description: "Apply for approval to install commercial or directional signage.",
    estimatedDays: 7,
  },
  {
    id: "service-15",
    tenantId: "tenant-beirut",
    title: "Graffiti or Vandalism Report",
    category: "Public Safety",
    description: "Report graffiti, vandalism, or damage to public assets.",
    estimatedDays: 5,
  },
  {
    id: "service-16",
    tenantId: "tenant-beirut",
    title: "Drainage Blockage Report",
    category: "Infrastructure",
    description: "Report blocked storm drains or flooding-prone street sections.",
    estimatedDays: 3,
  },
  {
    id: "service-17",
    tenantId: "tenant-beirut",
    title: "Noise Complaint",
    category: "Public Safety",
    description: "Submit a complaint about recurring noise disturbances.",
    estimatedDays: 4,
  },
];

export const serviceRequests: ServiceRequest[] = [
  {
    id: "req-1",
    tenantId: "tenant-beirut",
    reference: "BRT-2026-00124",
    title: "Residency Certificate for University Registration",
    status: "Under Review",
    priority: "Medium",
    submittedAt: "2026-04-02 09:20",
    updatedAt: "2026-04-05 14:10",
    department: "Civil Records",
    assignedReviewer: "Karim Nader",
    summary:
      "Certificate requested for academic enrollment and scholarship file.",
  },
  {
    id: "req-2",
    tenantId: "tenant-beirut",
    reference: "BRT-2026-00091",
    title: "Coffee Shop Permit Renewal",
    status: "Pending Documents",
    priority: "High",
    submittedAt: "2026-03-28 11:45",
    updatedAt: "2026-04-04 10:30",
    department: "Licensing",
    assignedReviewer: "Rana Khoury",
    summary: "Renewal request awaiting updated lease agreement.",
    isEscalated: true,
    escalatedAt: "2026-04-04 10:20",
  },
  {
    id: "req-3",
    tenantId: "tenant-beirut",
    reference: "BRT-2026-00065",
    title: "Noise and Construction Complaint",
    status: "Completed",
    priority: "Low",
    submittedAt: "2026-03-15 08:15",
    updatedAt: "2026-03-21 16:40",
    department: "Urban Management",
    assignedReviewer: "Karim Nader",
    summary:
      "Complaint investigated and closed with municipal inspection report.",
  },
];
